import Foundation

/// Additional equipment-specific variations expanding the built-in library.
enum ExerciseDatabaseExpansion {
    static let all: [Exercise] = [
        ex("smith-overhead-press", "Smith Machine Overhead Press", .shoulders, .barbell, .push, .verticalPush, family: .overheadPress, required: [.smithMachine], secondary: [.triceps], aliases: ["smith shoulder press"], suggestedAlternatives: ["dumbbell-shoulder-press", "machine-shoulder-press"]),
        ex("single-arm-dumbbell-overhead-press", "Single-Arm Dumbbell Overhead Press", .shoulders, .dumbbell, .push, .verticalPush, family: .overheadPress, required: [.dumbbells], secondary: [.triceps, .core], laterality: .unilateral, aliases: ["one arm overhead press", "single arm shoulder press"], weightInterpretation: .perArm, suggestedAlternatives: ["dumbbell-shoulder-press", "machine-shoulder-press"]),
        ex("dumbbell-skull-crusher", "Skull Crusher (Dumbbell)", .triceps, .dumbbell, .isolation, .isolation, family: .skullCrusher, required: [.dumbbells, .flatBench], aliases: ["db skull crusher", "dumbbell skull crusher", "skull crusher"], suggestedAlternatives: ["skull-crusher", "ez-bar-skull-crusher", "cable-skull-crusher"]),
        ex("ez-bar-skull-crusher", "Skull Crusher (EZ Bar)", .triceps, .barbell, .isolation, .isolation, family: .skullCrusher, required: [.ezCurlBar, .flatBench], aliases: ["ez skull crusher", "ez bar skull crusher", "skull crusher"], suggestedAlternatives: ["skull-crusher", "dumbbell-skull-crusher"]),
        ex("cable-skull-crusher", "Skull Crusher (Cable)", .triceps, .cable, .isolation, .isolation, family: .skullCrusher, required: [.cableStation, .flatBench], aliases: ["cable skull crusher", "skull crusher"], suggestedAlternatives: ["dumbbell-skull-crusher", "skull-crusher"]),
        ex("single-arm-dumbbell-tricep-extension", "Triceps Extension (Dumbbell)", .triceps, .dumbbell, .isolation, .isolation, family: .tricepExtension, required: [.dumbbells], laterality: .unilateral, aliases: ["one arm tricep extension", "dumbbell tricep extension", "tricep extension", "triceps extension"], weightInterpretation: .perArm, suggestedAlternatives: ["overhead-tricep-extension", "cable-overhead-extension"]),
        ex("rope-tricep-extension", "Triceps Extension (Rope)", .triceps, .cable, .isolation, .isolation, family: .tricepExtension, required: [.cableStation, .cableAttachments], aliases: ["rope overhead extension", "rope tricep extension", "tricep extension"], suggestedAlternatives: ["cable-overhead-extension", "rope-pushdown"]),
        ex("machine-tricep-extension", "Triceps Extension (Machine)", .triceps, .machine, .isolation, .isolation, family: .tricepExtension, required: [.tricepExtensionMachine], aliases: ["machine tricep extension", "tricep extension", "triceps extension"], weightInterpretation: .machineSetting, suggestedAlternatives: ["overhead-tricep-extension", "tricep-pushdown"]),
        ex("smith-bench-press", "Smith Machine Bench Press", .chest, .barbell, .push, .horizontalPush, family: .benchPress, required: [.smithMachine, .flatBench], secondary: [.shoulders, .triceps], aliases: ["smith bench"], suggestedAlternatives: ["barbell-bench-press", "dumbbell-bench-press", "chest-press-machine"]),
        ex("smith-incline-press", "Smith Machine Incline Press", .chest, .barbell, .push, .horizontalPush, family: .inclinePress, required: [.smithMachine, .adjustableBench], secondary: [.shoulders, .triceps], suggestedAlternatives: ["incline-barbell-press", "incline-dumbbell-press"]),
        ex("machine-row", "Machine Row", .back, .machine, .pull, .horizontalPull, family: .row, required: [.seatedRowMachine], secondary: [.biceps], aliases: ["row machine", "seated machine row"], weightInterpretation: .machineSetting, suggestedAlternatives: ["seated-cable-row", "one-arm-dumbbell-row", "barbell-row"]),
        ex("chest-supported-dumbbell-row", "Chest-Supported Dumbbell Row", .back, .dumbbell, .pull, .horizontalPull, family: .row, required: [.dumbbells, .adjustableBench], secondary: [.biceps], aliases: ["chest supported db row"], suggestedAlternatives: ["chest-supported-row", "one-arm-dumbbell-row"]),
        ex("smith-bent-over-row", "Smith Machine Bent-Over Row", .back, .barbell, .pull, .horizontalPull, family: .row, required: [.smithMachine], secondary: [.biceps], suggestedAlternatives: ["barbell-row", "one-arm-dumbbell-row"]),
        ex("dumbbell-donkey-kick", "Dumbbell Donkey Kick", .glutes, .dumbbell, .isolation, .isolation, family: .hipThrust, required: [.dumbbells], laterality: .unilateral, aliases: ["db donkey kick", "weighted donkey kick"], weightInterpretation: .perArm, suggestedAlternatives: ["cable-kickback", "band-glute-kickback", "quadruped-hip-extension"]),
        ex("band-glute-kickback", "Resistance Band Glute Kickback", .glutes, .bodyweight, .isolation, .isolation, family: .hipThrust, required: [.resistanceBands], laterality: .unilateral, aliases: ["band kickback"], measurement: .reps, suggestedAlternatives: ["cable-kickback", "dumbbell-donkey-kick", "quadruped-hip-extension"]),
        ex("quadruped-hip-extension", "Quadruped Hip Extension", .glutes, .bodyweight, .isolation, .isolation, family: .hipThrust, required: [.bodyweight], laterality: .unilateral, aliases: ["donkey kick bodyweight", "fire hydrant extension"], measurement: .reps, suggestedAlternatives: ["cable-kickback", "dumbbell-donkey-kick", "band-glute-kickback"]),
        ex("glute-focused-step-up", "Glute-Focused Step-Up", .glutes, .dumbbell, .lunge, .lunge, family: .lunge, required: [.dumbbells], laterality: .unilateral, aliases: ["glute step up"], suggestedAlternatives: ["step-up", "cable-kickback", "bulgarian-split-squat"]),
        ex("machine-glute-kickback", "Machine Glute Kickback", .glutes, .machine, .isolation, .isolation, family: .hipThrust, required: [.gluteKickbackMachine], laterality: .unilateral, weightInterpretation: .machineSetting, suggestedAlternatives: ["cable-kickback", "dumbbell-donkey-kick"]),
        ex("smith-squat-variation", "Smith Machine Squat", .quads, .barbell, .squat, .squat, family: .squat, required: [.smithMachine], secondary: [.glutes, .hamstrings]),
        ex("landmine-squat", "Landmine Squat", .quads, .barbell, .squat, .squat, family: .squat, required: [.barbell, .weightPlates], secondary: [.glutes]),
        ex("belt-squat", "Belt Squat", .quads, .machine, .squat, .squat, family: .squat, required: [.hackSquat], secondary: [.glutes]),
        ex("dumbbell-rdl", "Romanian Deadlift (Dumbbell)", .hamstrings, .dumbbell, .hinge, .hinge, family: .hinge, required: [.dumbbells], secondary: [.glutes, .back], aliases: ["dumbbell romanian deadlift", "db rdl", "rdl"]),
        ex("single-leg-rdl", "Single-Leg Romanian Deadlift", .hamstrings, .dumbbell, .hinge, .hinge, family: .hinge, required: [.dumbbells], secondary: [.glutes, .core], laterality: .unilateral),
        ex("cable-pull-through", "Cable Pull-Through", .glutes, .cable, .hinge, .hinge, family: .hinge, required: [.cableStation, .lowPulley], secondary: [.hamstrings]),
        ex("cable-hip-abduction", "Cable Hip Abduction", .glutes, .cable, .isolation, .isolation, family: .other, required: [.cableStation, .lowPulley], laterality: .unilateral),
        ex("band-hip-abduction", "Band Hip Abduction", .glutes, .bodyweight, .isolation, .isolation, family: .other, required: [.resistanceBands], laterality: .unilateral, measurement: .reps),
        ex("seated-hip-abduction", "Seated Hip Abduction", .glutes, .machine, .isolation, .isolation, family: .other, required: [.hipAbductor], weightInterpretation: .machineSetting),
        ex("seated-hip-adduction", "Seated Hip Adduction", .glutes, .machine, .isolation, .isolation, family: .other, required: [.hipAdductor], weightInterpretation: .machineSetting),
        ex("lying-leg-curl", "Lying Leg Curl", .hamstrings, .machine, .isolation, .isolation, family: .legCurl, required: [.lyingLegCurl], weightInterpretation: .machineSetting),
        ex("standing-calf-raise-machine", "Standing Calf Raise Machine", .calves, .machine, .isolation, .isolation, family: .calfRaise, required: [.calfRaiseMachine], weightInterpretation: .machineSetting),
        ex("seated-calf-raise-machine", "Seated Calf Raise Machine", .calves, .machine, .isolation, .isolation, family: .calfRaise, required: [.calfRaiseMachine], weightInterpretation: .machineSetting),
        ex("smith-calf-raise", "Smith Machine Calf Raise", .calves, .barbell, .isolation, .isolation, family: .calfRaise, required: [.smithMachine]),
        ex("dumbbell-calf-raise", "Dumbbell Calf Raise", .calves, .dumbbell, .isolation, .isolation, family: .calfRaise, required: [.dumbbells]),
        ex("cable-lateral-raise-single", "Single-Arm Cable Lateral Raise", .shoulders, .cable, .isolation, .isolation, family: .lateralRaise, required: [.cableStation, .lowPulley], laterality: .unilateral),
        ex("machine-lateral-raise", "Machine Lateral Raise", .shoulders, .machine, .isolation, .isolation, family: .lateralRaise, required: [.shoulderPressMachine], weightInterpretation: .machineSetting),
        ex("dumbbell-front-raise", "Dumbbell Front Raise", .shoulders, .dumbbell, .isolation, .isolation, family: .other, required: [.dumbbells], aliases: ["front raise db"]),
        ex("plate-front-raise", "Plate Front Raise", .shoulders, .barbell, .isolation, .isolation, family: .other, required: [.weightPlates]),
        ex("ez-bar-curl", "EZ-Bar Curl", .biceps, .barbell, .isolation, .isolation, family: .bicepCurl, required: [.ezCurlBar], aliases: ["ez curl"]),
        ex("cable-hammer-curl", "Cable Hammer Curl", .biceps, .cable, .isolation, .isolation, family: .bicepCurl, required: [.cableStation, .cableAttachments]),
        ex("machine-preacher-curl", "Machine Preacher Curl", .biceps, .machine, .isolation, .isolation, family: .bicepCurl, required: [.preacherCurlMachine], weightInterpretation: .machineSetting),
        ex("reverse-curl", "Reverse Curl", .biceps, .barbell, .isolation, .isolation, family: .bicepCurl, required: [.barbell, .ezCurlBar], aliases: ["reverse barbell curl"]),
        ex("wrist-curl", "Wrist Curl", .biceps, .dumbbell, .isolation, .isolation, family: .other, required: [.dumbbells]),
        ex("reverse-wrist-curl", "Reverse Wrist Curl", .biceps, .dumbbell, .isolation, .isolation, family: .other, required: [.dumbbells]),
        ex("close-grip-lat-pulldown", "Close-Grip Lat Pulldown", .back, .cable, .pull, .verticalPull, family: .pulldown, required: [.latPulldownMachine], secondary: [.biceps], aliases: ["close grip pulldown"]),
        ex("neutral-grip-pulldown", "Neutral-Grip Lat Pulldown", .back, .cable, .pull, .verticalPull, family: .pulldown, required: [.latPulldownMachine], secondary: [.biceps]),
        ex("straight-arm-cable-pulldown", "Straight Arm Pulldown (Cable)", .back, .cable, .isolation, .isolation, family: .pulldown, required: [.cableStation, .highPulley], secondary: [.triceps], aliases: ["straight arm pulldown", "straight-arm pulldown", "lat"]),
        ex("band-pulldown", "Lat Pulldown (Band)", .back, .bodyweight, .pull, .verticalPull, family: .pulldown, required: [.resistanceBands], secondary: [.biceps], aliases: ["band lat pulldown", "band pulldown", "lat"], measurement: .reps),
        ex("trx-row", "Suspension Trainer Row", .back, .bodyweight, .pull, .horizontalPull, family: .row, required: [.suspensionTrainer], secondary: [.biceps], aliases: ["trx row"], measurement: .reps),
        ex("trx-push-up", "Suspension Trainer Push-Up", .chest, .bodyweight, .push, .horizontalPush, family: .benchPress, required: [.suspensionTrainer], secondary: [.shoulders, .triceps], measurement: .reps),
        ex("trx-squat", "Suspension Trainer Squat", .quads, .bodyweight, .squat, .squat, family: .squat, required: [.suspensionTrainer], secondary: [.glutes], measurement: .reps),
        ex("medicine-ball-slam", "Medicine Ball Slam", .fullBody, .bodyweight, .conditioning, .conditioning, family: .other, required: [.medicineBall], secondary: [.core], measurement: .reps),
        ex("stability-ball-crunch", "Stability Ball Crunch", .core, .bodyweight, .core, .core, family: .core, required: [.stabilityBall], measurement: .reps),
        ex("stability-ball-hip-thrust", "Stability Ball Hip Thrust", .glutes, .bodyweight, .hinge, .hinge, family: .hipThrust, required: [.stabilityBall], secondary: [.hamstrings], measurement: .reps),
        ex("band-pull-apart", "Band Pull-Apart", .shoulders, .bodyweight, .isolation, .isolation, family: .other, required: [.resistanceBands], secondary: [.back], measurement: .reps),
        ex("band-chest-press", "Band Chest Press", .chest, .bodyweight, .push, .horizontalPush, family: .benchPress, required: [.resistanceBands], secondary: [.triceps, .shoulders], measurement: .reps),
        ex("band-row", "Band Row", .back, .bodyweight, .pull, .horizontalPull, family: .row, required: [.resistanceBands], secondary: [.biceps], measurement: .reps),
        ex("band-squat", "Band Squat", .quads, .bodyweight, .squat, .squat, family: .squat, required: [.resistanceBands], secondary: [.glutes], measurement: .reps),
        ex("goblet-lateral-lunge", "Goblet Lateral Lunge", .quads, .dumbbell, .lunge, .lunge, family: .lunge, required: [.dumbbells], secondary: [.glutes], laterality: .alternating),
        ex("reverse-lunge", "Reverse Lunge", .quads, .dumbbell, .lunge, .lunge, family: .lunge, required: [.dumbbells], secondary: [.glutes], laterality: .unilateral),
        ex("curtsy-lunge", "Curtsy Lunge", .glutes, .dumbbell, .lunge, .lunge, family: .lunge, required: [.dumbbells], secondary: [.quads], laterality: .unilateral),
        ex("deficit-push-up", "Deficit Push-Up", .chest, .bodyweight, .push, .horizontalPush, family: .benchPress, required: [.bodyweight], secondary: [.triceps, .shoulders], measurement: .reps),
        ex("diamond-push-up", "Diamond Push-Up", .triceps, .bodyweight, .push, .horizontalPush, family: .tricepExtension, required: [.bodyweight], secondary: [.chest], aliases: ["triangle push up"], measurement: .reps),
        ex("pike-push-up", "Pike Push-Up", .shoulders, .bodyweight, .push, .verticalPush, family: .overheadPress, required: [.bodyweight], secondary: [.triceps], measurement: .reps),
        ex("handstand-push-up", "Handstand Push-Up", .shoulders, .bodyweight, .push, .verticalPush, family: .overheadPress, required: [.bodyweight], secondary: [.triceps], aliases: ["hspu"], measurement: .reps),
        ex("ring-dip", "Ring Dip", .chest, .bodyweight, .push, .verticalPush, family: .benchPress, required: [.suspensionTrainer], secondary: [.triceps], measurement: .bodyweight),
        ex("chest-supported-incline-row", "Chest-Supported Incline Row", .back, .dumbbell, .pull, .horizontalPull, family: .row, required: [.dumbbells, .adjustableBench], secondary: [.biceps]),
        ex("seal-row", "Seal Row", .back, .barbell, .pull, .horizontalPull, family: .row, required: [.barbell, .flatBench], secondary: [.biceps]),
        ex("yates-row", "Yates Row", .back, .barbell, .pull, .horizontalPull, family: .row, required: [.barbell, .weightPlates], secondary: [.biceps]),
        ex("cable-face-pull", "Cable Face Pull", .shoulders, .cable, .isolation, .isolation, family: .other, required: [.cableStation, .highPulley, .cableAttachments], secondary: [.back], aliases: ["face pull cable"]),
        ex("band-face-pull", "Band Face Pull", .shoulders, .bodyweight, .isolation, .isolation, family: .other, required: [.resistanceBands], secondary: [.back], measurement: .reps),
        ex("machine-hip-thrust", "Hip Thrust (Machine)", .glutes, .machine, .hinge, .hinge, family: .hipThrust, required: [.hipThrustMachine], secondary: [.hamstrings], aliases: ["machine hip thrust", "hip thrust", "glute"], weightInterpretation: .machineSetting),
        ex("single-leg-hip-thrust", "Single-Leg Hip Thrust", .glutes, .bodyweight, .hinge, .hinge, family: .hipThrust, required: [.bodyweight, .flatBench], secondary: [.hamstrings], laterality: .unilateral, measurement: .reps),
        ex("dumbbell-hip-thrust", "Hip Thrust (Dumbbell)", .glutes, .dumbbell, .hinge, .hinge, family: .hipThrust, required: [.dumbbells, .flatBench], secondary: [.hamstrings], aliases: ["dumbbell hip thrust", "db hip thrust", "hip thrust", "glute"]),
        ex("cable-crunch-kneeling", "Kneeling Cable Crunch", .core, .cable, .core, .core, family: .core, required: [.cableStation, .highPulley]),
        ex("hanging-knee-raise", "Hanging Knee Raise", .core, .bodyweight, .core, .core, family: .core, required: [.pullUpBar], measurement: .reps),
        ex("captains-chair-leg-raise", "Captain's Chair Leg Raise", .core, .machine, .core, .core, family: .core, required: [.assistedPullUpMachine], measurement: .reps),
        ex("ab-machine-crunch", "Ab Crunch Machine", .core, .machine, .core, .core, family: .core, required: [.chestPressMachine], weightInterpretation: .machineSetting),
        ex("pallof-press-band", "Band Pallof Press", .core, .bodyweight, .core, .rotation, family: .core, required: [.resistanceBands], measurement: .reps),
        ex("farmer-carry-kettlebell", "Kettlebell Farmer's Carry", .fullBody, .kettlebell, .carry, .carry, family: .carry, required: [.kettlebells], secondary: [.core, .core], measurement: .weightAndTime, weightInterpretation: .perHand, tracking: .weightTimeSets(primary: .time, mode: .primary, weightKg: 2.5, seconds: 5)),
        ex("front-rack-carry", "Front-Rack Carry", .fullBody, .barbell, .carry, .carry, family: .carry, required: [.barbell], secondary: [.core, .shoulders], measurement: .distance),
        ex("zercher-squat", "Zercher Squat", .quads, .barbell, .squat, .squat, family: .squat, required: [.barbell, .weightPlates], secondary: [.core, .glutes]),
        ex("safety-bar-squat", "Safety-Bar Squat", .quads, .barbell, .squat, .squat, family: .squat, required: [.barbell, .squatRack], secondary: [.glutes]),
        ex("box-squat", "Box Squat", .quads, .barbell, .squat, .squat, family: .squat, required: [.barbell, .squatRack], secondary: [.glutes, .hamstrings]),
        ex("pause-bench-press", "Pause Bench Press", .chest, .barbell, .push, .horizontalPush, family: .benchPress, required: [.barbell, .flatBench, .weightPlates], secondary: [.triceps, .shoulders]),
        ex("spoto-press", "Spoto Press", .chest, .barbell, .push, .horizontalPush, family: .benchPress, required: [.barbell, .flatBench], secondary: [.triceps]),
        ex("jm-press", "JM Press", .triceps, .barbell, .push, .horizontalPush, family: .tricepExtension, required: [.barbell, .flatBench], secondary: [.chest]),
        ex("tate-press", "Tate Press", .triceps, .dumbbell, .isolation, .isolation, family: .tricepExtension, required: [.dumbbells, .flatBench]),
        ex("kickback-cable", "Cable Tricep Kickback", .triceps, .cable, .isolation, .isolation, family: .tricepExtension, required: [.cableStation, .lowPulley], laterality: .unilateral),
        ex("overhead-cable-curl", "Overhead Cable Curl", .biceps, .cable, .isolation, .isolation, family: .bicepCurl, required: [.cableStation, .highPulley]),
        ex("cross-body-hammer-curl", "Cross-Body Hammer Curl", .biceps, .dumbbell, .isolation, .isolation, family: .bicepCurl, required: [.dumbbells], laterality: .alternating),
        ex("zottman-curl", "Zottman Curl", .biceps, .dumbbell, .isolation, .isolation, family: .bicepCurl, required: [.dumbbells]),
        ex("drag-curl", "Drag Curl", .biceps, .barbell, .isolation, .isolation, family: .bicepCurl, required: [.barbell]),
        ex("machine-chest-press-incline", "Incline Machine Chest Press", .chest, .machine, .push, .horizontalPush, family: .inclinePress, required: [.chestPressMachine], secondary: [.shoulders, .triceps], weightInterpretation: .machineSetting),
        ex("pec-deck-rear", "Rear Delt Pec Deck", .shoulders, .machine, .isolation, .isolation, family: .other, required: [.rearDeltMachine], secondary: [.back], weightInterpretation: .machineSetting),
        ex("cable-rear-delt-fly", "Cable Rear Delt Fly", .shoulders, .cable, .isolation, .isolation, family: .other, required: [.cableStation], secondary: [.back]),
        ex("bent-over-lateral-raise", "Bent-Over Lateral Raise", .shoulders, .dumbbell, .isolation, .isolation, family: .lateralRaise, required: [.dumbbells], secondary: [.back], aliases: ["rear delt raise"]),
        ex("lu-raise", "Lu Raise", .shoulders, .dumbbell, .isolation, .isolation, family: .lateralRaise, required: [.dumbbells]),
        ex("scaption", "Dumbbell Scaption", .shoulders, .dumbbell, .isolation, .isolation, family: .lateralRaise, required: [.dumbbells]),
        ex("meadows-row-landmine", "Landmine Meadows Row", .back, .barbell, .pull, .horizontalPull, family: .row, required: [.barbell, .weightPlates], secondary: [.biceps], laterality: .unilateral),
        ex("helms-row", "Helms Row", .back, .dumbbell, .pull, .horizontalPull, family: .row, required: [.dumbbells, .adjustableBench], secondary: [.biceps]),
        ex("kroc-row", "Kroc Row", .back, .dumbbell, .pull, .horizontalPull, family: .row, required: [.dumbbells], secondary: [.biceps, .core], laterality: .unilateral),
        ex("pendlay-row-variation", "Wide-Grip Pendlay Row", .back, .barbell, .pull, .horizontalPull, family: .row, required: [.barbell, .weightPlates], secondary: [.biceps]),
        ex("snatch-grip-deadlift", "Snatch-Grip Deadlift", .back, .barbell, .hinge, .hinge, family: .hinge, required: [.barbell, .weightPlates], secondary: [.hamstrings, .glutes]),
        ex("deficit-deadlift", "Deficit Deadlift", .back, .barbell, .hinge, .hinge, family: .hinge, required: [.barbell, .weightPlates], secondary: [.hamstrings, .glutes]),
        ex("stiff-leg-deadlift", "Stiff-Leg Deadlift", .hamstrings, .barbell, .hinge, .hinge, family: .hinge, required: [.barbell, .weightPlates], secondary: [.glutes, .back], aliases: ["sldl"]),
        ex("good-morning", "Good Morning", .hamstrings, .barbell, .hinge, .hinge, family: .hinge, required: [.barbell, .squatRack], secondary: [.back, .glutes]),
        ex("back-extension-machine", "Machine Back Extension", .back, .machine, .hinge, .hinge, family: .hinge, required: [.backExtensionBench], secondary: [.glutes, .hamstrings], weightInterpretation: .machineSetting),
        ex("45-degree-hyper", "45-Degree Hyperextension", .back, .bodyweight, .hinge, .hinge, family: .hinge, required: [.backExtensionBench], secondary: [.glutes, .hamstrings], measurement: .reps),
        ex("reverse-hyper", "Reverse Hyperextension", .glutes, .machine, .hinge, .hinge, family: .hipThrust, required: [.backExtensionBench], secondary: [.hamstrings], measurement: .reps),
        ex("glute-bridge", "Glute Bridge", .glutes, .bodyweight, .hinge, .hinge, family: .hipThrust, required: [.bodyweight], secondary: [.hamstrings], measurement: .reps),
        ex("single-leg-glute-bridge", "Single-Leg Glute Bridge", .glutes, .bodyweight, .hinge, .hinge, family: .hipThrust, required: [.bodyweight], secondary: [.hamstrings], laterality: .unilateral, measurement: .reps),
        ex("frog-pump", "Frog Pump", .glutes, .bodyweight, .isolation, .isolation, family: .hipThrust, required: [.bodyweight], measurement: .reps),
        ex("cable-squat", "Cable Squat", .quads, .cable, .squat, .squat, family: .squat, required: [.cableStation, .lowPulley], secondary: [.glutes]),
        ex("landmine-press-single", "Single-Arm Landmine Press", .shoulders, .barbell, .push, .verticalPush, family: .overheadPress, required: [.barbell, .weightPlates], secondary: [.triceps, .core], laterality: .unilateral),
        ex("viking-press", "Viking Press", .shoulders, .machine, .push, .verticalPush, family: .overheadPress, required: [.shoulderPressMachine], secondary: [.triceps], weightInterpretation: .machineSetting),
        ex("log-press", "Log Press", .shoulders, .barbell, .push, .verticalPush, family: .overheadPress, required: [.barbell], secondary: [.triceps]),
        ex("bradford-press", "Bradford Press", .shoulders, .barbell, .push, .verticalPush, family: .overheadPress, required: [.barbell], secondary: [.triceps]),
        ex("cuban-press", "Cuban Press", .shoulders, .dumbbell, .isolation, .isolation, family: .other, required: [.dumbbells]),
        ex("external-rotation", "Dumbbell External Rotation", .shoulders, .dumbbell, .isolation, .isolation, family: .other, required: [.dumbbells], laterality: .unilateral),
        ex("cable-external-rotation", "Cable External Rotation", .shoulders, .cable, .isolation, .isolation, family: .other, required: [.cableStation], laterality: .unilateral),
        ex("sissy-squat", "Sissy Squat", .quads, .bodyweight, .squat, .squat, family: .squat, required: [.bodyweight], measurement: .reps),
        ex("spanish-squat", "Spanish Squat", .quads, .bodyweight, .squat, .squat, family: .squat, required: [.resistanceBands], measurement: .reps),
        ex("v-squat", "V-Squat", .quads, .machine, .squat, .squat, family: .squat, required: [.hackSquat], secondary: [.glutes], weightInterpretation: .machineSetting),
        ex("pendulum-squat", "Pendulum Squat", .quads, .machine, .squat, .squat, family: .squat, required: [.hackSquat], secondary: [.glutes], weightInterpretation: .machineSetting),
        ex("leg-press-narrow", "Narrow-Stance Leg Press", .quads, .machine, .squat, .squat, family: .legExtension, required: [.legPress], secondary: [.glutes], weightInterpretation: .machineSetting),
        ex("leg-press-wide", "Wide-Stance Leg Press", .glutes, .machine, .squat, .squat, family: .squat, required: [.legPress], secondary: [.quads, .hamstrings], weightInterpretation: .machineSetting),
        ex("single-leg-press", "Single-Leg Press", .quads, .machine, .squat, .squat, family: .squat, required: [.legPress], secondary: [.glutes], laterality: .unilateral, weightInterpretation: .machineSetting),
        ex("leg-extension-single", "Single-Leg Extension", .quads, .machine, .isolation, .isolation, family: .legExtension, required: [.legExtension], laterality: .unilateral, weightInterpretation: .machineSetting),
        ex("nordic-curl", "Nordic Hamstring Curl", .hamstrings, .bodyweight, .isolation, .isolation, family: .legCurl, required: [.bodyweight], measurement: .reps),
        ex("swiss-ball-leg-curl", "Stability Ball Leg Curl", .hamstrings, .bodyweight, .isolation, .isolation, family: .legCurl, required: [.stabilityBall], secondary: [.glutes], measurement: .reps),
        ex("slider-leg-curl", "Slider Leg Curl", .hamstrings, .bodyweight, .isolation, .isolation, family: .legCurl, required: [.bodyweight], secondary: [.glutes], measurement: .reps),
        ex("cable-kickback-straight", "Straight-Leg Cable Kickback", .glutes, .cable, .isolation, .isolation, family: .hipThrust, required: [.cableStation, .lowPulley], laterality: .unilateral),
        ex("ankle-weight-kickback", "Ankle-Weight Kickback", .glutes, .bodyweight, .isolation, .isolation, family: .hipThrust, required: [.bodyweight], laterality: .unilateral, measurement: .reps),
        ex("barbell-glute-bridge", "Barbell Glute Bridge", .glutes, .barbell, .hinge, .hinge, family: .hipThrust, required: [.barbell, .weightPlates], secondary: [.hamstrings]),
        ex("kas-glute-bridge", "KAS Glute Bridge", .glutes, .barbell, .hinge, .hinge, family: .hipThrust, required: [.barbell, .weightPlates, .flatBench], secondary: [.hamstrings]),
        ex("b-stance-rdl", "B-Stance Romanian Deadlift", .hamstrings, .dumbbell, .hinge, .hinge, family: .hinge, required: [.dumbbells], secondary: [.glutes], laterality: .unilateral),
        ex("cable-rdl", "Cable Romanian Deadlift", .hamstrings, .cable, .hinge, .hinge, family: .hinge, required: [.cableStation, .lowPulley], secondary: [.glutes, .back]),
        ex("smith-rdl", "Smith Machine Romanian Deadlift", .hamstrings, .barbell, .hinge, .hinge, family: .hinge, required: [.smithMachine], secondary: [.glutes, .back]),
        ex("trap-bar-deadlift", "Trap-Bar Deadlift", .fullBody, .barbell, .hinge, .hinge, family: .hinge, required: [.barbell, .weightPlates], secondary: [.quads, .glutes, .back], aliases: ["hex bar deadlift"]),
        ex("jefferson-deadlift", "Jefferson Deadlift", .fullBody, .barbell, .hinge, .hinge, family: .hinge, required: [.barbell, .weightPlates], secondary: [.quads, .glutes]),
        ex("suitcase-deadlift", "Suitcase Deadlift", .fullBody, .dumbbell, .hinge, .hinge, family: .hinge, required: [.dumbbells], secondary: [.core, .back], laterality: .unilateral),
        ex("waiters-carry", "Waiter's Carry", .fullBody, .dumbbell, .carry, .carry, family: .carry, required: [.dumbbells], secondary: [.shoulders, .core], laterality: .unilateral, measurement: .distance),
        ex("rack-carry", "Rack Carry", .fullBody, .barbell, .carry, .carry, family: .carry, required: [.barbell, .squatRack], secondary: [.core], measurement: .distance),
        ex("yoke-carry", "Yoke Carry", .fullBody, .barbell, .carry, .carry, family: .carry, required: [.barbell], secondary: [.core, .quads], measurement: .distance),
        ex("sled-drag", "Sled Drag", .fullBody, .machine, .conditioning, .conditioning, family: .other, required: [.bodyweight], secondary: [.quads, .glutes], measurement: .distance),
        ex("prowler-push", "Prowler Push", .fullBody, .machine, .conditioning, .conditioning, family: .other, required: [.bodyweight], secondary: [.quads, .glutes], measurement: .distance),
        ex("assault-bike", "Assault Bike", .fullBody, .machine, .conditioning, .conditioning, family: .other, required: [.bodyweight], measurement: .time),
        ex("ski-erg", "SkiErg", .fullBody, .machine, .conditioning, .conditioning, family: .other, required: [.bodyweight], secondary: [.back, .core], measurement: .time),
        ex("jump-rope", "Jump Rope", .fullBody, .bodyweight, .conditioning, .conditioning, family: .other, required: [.bodyweight], secondary: [.calves], measurement: .time),
        ex("high-knees", "High Knees", .fullBody, .bodyweight, .conditioning, .conditioning, family: .other, required: [.bodyweight], measurement: .time),
        ex("mountain-climber-slow", "Slow Mountain Climber", .core, .bodyweight, .core, .core, family: .core, required: [.bodyweight], measurement: .reps),
        ex("dead-bug-band", "Band Dead Bug", .core, .bodyweight, .core, .core, family: .core, required: [.resistanceBands], measurement: .reps),
        ex("bird-dog-row", "Bird-Dog Row", .back, .dumbbell, .pull, .horizontalPull, family: .row, required: [.dumbbells], secondary: [.core], laterality: .unilateral),
        ex("renegade-row", "Renegade Row", .back, .dumbbell, .pull, .horizontalPull, family: .row, required: [.dumbbells], secondary: [.core, .shoulders], laterality: .alternating),
        ex("push-up-to-row", "Push-Up to Row", .fullBody, .dumbbell, .push, .horizontalPush, family: .other, required: [.dumbbells], secondary: [.back, .core], laterality: .alternating),
        ex("thruster-dumbbell", "Dumbbell Thruster", .fullBody, .dumbbell, .conditioning, .conditioning, family: .other, required: [.dumbbells], secondary: [.shoulders, .quads]),
        ex("man-maker", "Man Maker", .fullBody, .dumbbell, .conditioning, .conditioning, family: .other, required: [.dumbbells], secondary: [.back, .shoulders, .core]),
        ex("devil-press", "Devil Press", .fullBody, .dumbbell, .conditioning, .conditioning, family: .other, required: [.dumbbells], secondary: [.shoulders, .core]),
        ex("turkish-get-up", "Turkish Get-Up", .fullBody, .kettlebell, .conditioning, .conditioning, family: .other, required: [.kettlebells], secondary: [.core, .shoulders], laterality: .unilateral),
        ex("kettlebell-goblet-squat", "Kettlebell Goblet Squat", .quads, .kettlebell, .squat, .squat, family: .squat, required: [.kettlebells], secondary: [.glutes, .core]),
        ex("kettlebell-rdl", "Kettlebell Romanian Deadlift", .hamstrings, .kettlebell, .hinge, .hinge, family: .hinge, required: [.kettlebells], secondary: [.glutes, .back]),
        ex("kettlebell-row", "Kettlebell Row", .back, .kettlebell, .pull, .horizontalPull, family: .row, required: [.kettlebells], secondary: [.biceps], laterality: .unilateral),
        ex("kettlebell-press", "Kettlebell Overhead Press", .shoulders, .kettlebell, .push, .verticalPush, family: .overheadPress, required: [.kettlebells], secondary: [.triceps], laterality: .unilateral, weightInterpretation: .perArm),
        ex("kettlebell-clean-and-press", "Kettlebell Clean and Press", .fullBody, .kettlebell, .olympic, .olympic, family: .other, required: [.kettlebells], secondary: [.shoulders, .core], laterality: .unilateral),
        ex("goblet-march", "Goblet March", .core, .dumbbell, .core, .core, family: .core, required: [.dumbbells], secondary: [.glutes], measurement: .time),
        ex("suitcase-march", "Suitcase March", .core, .dumbbell, .core, .core, family: .core, required: [.dumbbells], laterality: .unilateral, measurement: .time),
        ex("copenhagen-adductor", "Copenhagen Adductor Raise", .glutes, .bodyweight, .isolation, .isolation, family: .other, required: [.bodyweight, .flatBench], laterality: .unilateral, measurement: .reps),
        ex("side-plank-hip-abduction", "Side Plank Hip Abduction", .glutes, .bodyweight, .isolation, .isolation, family: .other, required: [.bodyweight], secondary: [.core], laterality: .unilateral, measurement: .reps),
        ex("clam-shell", "Clamshell", .glutes, .bodyweight, .isolation, .isolation, family: .other, required: [.resistanceBands], laterality: .unilateral, measurement: .reps),
        ex("monster-walk", "Monster Walk", .glutes, .bodyweight, .isolation, .isolation, family: .other, required: [.resistanceBands], measurement: .reps),
        ex("lateral-band-walk", "Lateral Band Walk", .glutes, .bodyweight, .isolation, .isolation, family: .other, required: [.resistanceBands], measurement: .reps),
        ex("fire-hydrant", "Fire Hydrant", .glutes, .bodyweight, .isolation, .isolation, family: .other, required: [.bodyweight], laterality: .unilateral, measurement: .reps),
        ex("donkey-kick-bodyweight", "Bodyweight Donkey Kick", .glutes, .bodyweight, .isolation, .isolation, family: .hipThrust, required: [.bodyweight], laterality: .unilateral, measurement: .reps),
    ]

    private static func ex(
        _ id: String,
        _ name: String,
        _ primary: MuscleGroup,
        _ equipment: EquipmentType,
        _ category: ExerciseCategory,
        _ pattern: MovementPattern,
        family: MovementFamily,
        required: [GymEquipmentKind],
        secondary: [MuscleGroup] = [],
        laterality: Laterality = .bilateral,
        aliases: [String] = [],
        measurement: MeasurementUnit? = nil,
        progression: ProgressionMethod? = nil,
        overload: Bool? = nil,
        weightInterpretation: WeightInterpretation? = nil,
        suggestedAlternatives: [String] = [],
        tracking: ExerciseTrackingProfile? = nil
    ) -> Exercise {
        Exercise(
            id: id,
            name: name,
            aliases: aliases,
            primaryMuscleGroup: primary,
            secondaryMuscleGroups: secondary,
            equipment: equipment,
            category: category,
            movementPattern: pattern,
            laterality: laterality,
            measurementUnit: measurement,
            trackingProfile: tracking,
            progressionMethod: progression,
            supportsProgressiveOverload: overload,
            movementFamily: family,
            requiredEquipment: required,
            suggestedAlternatives: suggestedAlternatives,
            weightInterpretation: weightInterpretation
        )
    }
}

