import type { Exercise } from '../types'

export const SEED_EXERCISES: Omit<Exercise, 'id'>[] = [
  { name: 'Barbell Back Squat', muscleGroup: 'Legs', equipment: 'Barbell' },
  { name: 'Romanian Deadlift', muscleGroup: 'Hamstrings', equipment: 'Barbell' },
  { name: 'Hip Thrust', muscleGroup: 'Glutes', equipment: 'Barbell' },
  { name: 'Bulgarian Split Squat', muscleGroup: 'Legs', equipment: 'Dumbbell' },
  { name: 'Leg Press', muscleGroup: 'Legs', equipment: 'Machine' },
  { name: 'Walking Lunges', muscleGroup: 'Legs', equipment: 'Dumbbell' },
  { name: 'Barbell Bench Press', muscleGroup: 'Chest', equipment: 'Barbell' },
  { name: 'Dumbbell Bench Press', muscleGroup: 'Chest', equipment: 'Dumbbell' },
  { name: 'Incline Dumbbell Press', muscleGroup: 'Chest', equipment: 'Dumbbell' },
  { name: 'Cable Fly', muscleGroup: 'Chest', equipment: 'Cable' },
  { name: 'Push-Up', muscleGroup: 'Chest', equipment: 'Bodyweight' },
  { name: 'Lat Pulldown', muscleGroup: 'Back', equipment: 'Cable' },
  { name: 'Seated Cable Row', muscleGroup: 'Back', equipment: 'Cable' },
  { name: 'Barbell Row', muscleGroup: 'Back', equipment: 'Barbell' },
  { name: 'Dumbbell Row', muscleGroup: 'Back', equipment: 'Dumbbell' },
  { name: 'Pull-Up', muscleGroup: 'Back', equipment: 'Bodyweight' },
  { name: 'Overhead Press', muscleGroup: 'Shoulders', equipment: 'Barbell' },
  { name: 'Dumbbell Shoulder Press', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
  { name: 'Lateral Raise', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
  { name: 'Face Pull', muscleGroup: 'Shoulders', equipment: 'Cable' },
  { name: 'Barbell Curl', muscleGroup: 'Biceps', equipment: 'Barbell' },
  { name: 'Dumbbell Curl', muscleGroup: 'Biceps', equipment: 'Dumbbell' },
  { name: 'Hammer Curl', muscleGroup: 'Biceps', equipment: 'Dumbbell' },
  { name: 'Tricep Pushdown', muscleGroup: 'Triceps', equipment: 'Cable' },
  { name: 'Skull Crusher', muscleGroup: 'Triceps', equipment: 'Barbell' },
  { name: 'Overhead Tricep Extension', muscleGroup: 'Triceps', equipment: 'Dumbbell' },
  { name: 'Plank', muscleGroup: 'Core', equipment: 'Bodyweight' },
  { name: 'Cable Crunch', muscleGroup: 'Core', equipment: 'Cable' },
  { name: 'Dead Bug', muscleGroup: 'Core', equipment: 'Bodyweight' },
  { name: 'Kettlebell Swing', muscleGroup: 'Full Body', equipment: 'Kettlebell' },
  { name: 'Goblet Squat', muscleGroup: 'Legs', equipment: 'Dumbbell' },
  { name: 'Step-Up', muscleGroup: 'Legs', equipment: 'Dumbbell' },
]
