import Foundation

/// Display names for built-in exercises.
/// Keys are stable exercise IDs (canonical English database).
/// Custom / user-created exercises are never looked up here.
/// MVP is English-only; per-language maps can return later.
enum ExerciseLocalizations {
    static let englishNames: [String: String] = [
            "barbell-bench-press": "Barbell Bench Press",
            "dumbbell-bench-press": "Dumbbell Bench Press",
            "incline-barbell-press": "Incline Barbell Press",
            "incline-dumbbell-press": "Incline Dumbbell Press",
            "decline-barbell-press": "Decline Barbell Press",
            "decline-dumbbell-press": "Decline Dumbbell Press",
            "floor-press": "Floor Press",
            "chest-press-machine": "Chest Press Machine",
            "pec-deck": "Pec Deck",
            "machine-chest-fly": "Machine Chest Fly",
            "cable-fly": "Cable Fly",
            "low-cable-fly": "Low Cable Fly",
            "dumbbell-fly": "Dumbbell Fly",
            "incline-dumbbell-fly": "Incline Dumbbell Fly",
            "landmine-press": "Landmine Press",
            "svend-press": "Svend Press",
            "push-up": "Push-Up",
            "incline-push-up": "Incline Push-Up",
            "decline-push-up": "Decline Push-Up",
            "chest-dip": "Chest Dip",
            "weighted-dip": "Weighted Dip",
            "pull-up": "Pull-Up",
            "chin-up": "Chin-Up",
            "assisted-pull-up": "Assisted Pull-Up",
            "lat-pulldown": "Lat Pulldown (Cable)",
            "wide-grip-pulldown": "Wide-Grip Pulldown",
            "close-grip-pulldown": "Close-Grip Pulldown",
            "straight-arm-pulldown": "Straight Arm Pulldown (Cable)",
            "barbell-row": "Barbell Row",
            "pendlay-row": "Pendlay Row",
            "one-arm-dumbbell-row": "One-Arm Dumbbell Row",
            "chest-supported-row": "Chest-Supported Row",
            "vertical-row": "Vertical Row",
            "seated-cable-row": "Seated Cable Row",
            "single-arm-cable-row": "Single-Arm Cable Row",
            "t-bar-row": "T-Bar Row",
            "meadows-row": "Meadows Row",
            "inverted-row": "Inverted Row",
            "rack-pull": "Rack Pull",
            "conventional-deadlift": "Conventional Deadlift",
            "sumo-deadlift": "Sumo Deadlift",
            "back-extension": "Back Extension",
            "face-pull": "Face Pull",
            "overhead-press": "Overhead Press",
            "push-press": "Push Press",
            "dumbbell-shoulder-press": "Dumbbell Shoulder Press",
            "arnold-press": "Arnold Press",
            "machine-shoulder-press": "Machine Shoulder Press",
            "behind-neck-press": "Behind-Neck Press",
            "lateral-raise": "Lateral Raise",
            "cable-lateral-raise": "Cable Lateral Raise",
            "front-raise": "Front Raise",
            "cable-front-raise": "Cable Front Raise",
            "reverse-fly": "Reverse Fly",
            "reverse-pec-deck": "Reverse Pec Deck",
            "upright-row": "Upright Row",
            "barbell-shrug": "Barbell Shrug",
            "dumbbell-shrug": "Dumbbell Shrug",
            "landmine-lateral-raise": "Landmine Lateral Raise",
            "barbell-curl": "Barbell Curl",
            "dumbbell-curl": "Dumbbell Curl",
            "hammer-curl": "Hammer Curl",
            "incline-dumbbell-curl": "Incline Dumbbell Curl",
            "preacher-curl": "Preacher Curl",
            "spider-curl": "Spider Curl",
            "cable-curl": "Cable Curl",
            "concentration-curl": "Concentration Curl",
            "tricep-pushdown": "Tricep Pushdown",
            "rope-pushdown": "Rope Tricep Pushdown",
            "tricep-extension": "Triceps Extension (Cable)",
            "skull-crusher": "Skull Crusher (Barbell)",
            "overhead-tricep-extension": "Overhead Triceps Extension (Dumbbell)",
            "cable-overhead-extension": "Cable Overhead Extension",
            "dumbbell-tricep-kickback": "Dumbbell Tricep Kickback",
            "close-grip-bench": "Close-Grip Bench Press",
            "tricep-dip": "Tricep Dip",
            "barbell-back-squat": "Barbell Back Squat",
            "front-squat": "Front Squat",
            "goblet-squat": "Goblet Squat",
            "hack-squat": "Hack Squat",
            "leg-press": "Leg Press",
            "belt-squat": "Belt Squat",
            "smith-squat": "Smith Machine Squat",
            "pendulum-squat": "Pendulum Squat",
            "leg-extension": "Leg Extension",
            "hip-thrust": "Hip Thrust (Barbell)",
            "smith-hip-thrust": "Hip Thrust (Smith)",
            "glute-bridge": "Glute Bridge (Bodyweight)",
            "single-leg-glute-bridge": "Single-Leg Glute Bridge",
            "cable-kickback": "Glute Kickback (Cable)",
            "hip-abduction": "Hip Abduction",
            "hip-adduction": "Hip Adduction",
            "forward-lunge": "Forward Lunge",
            "walking-lunge": "Walking Lunge",
            "reverse-lunge": "Reverse Lunge",
            "bulgarian-split-squat": "Bulgarian Split Squat",
            "step-up": "Step-Up",
            "sissy-squat": "Sissy Squat",
            "romanian-deadlift": "Romanian Deadlift (Barbell)",
            "dumbbell-rdl": "Romanian Deadlift (Dumbbell)",
            "single-leg-rdl": "Single-Leg Romanian Deadlift",
            "stiff-leg-deadlift": "Stiff-Leg Deadlift",
            "leg-curl": "Leg Curl",
            "seated-leg-curl": "Seated Leg Curl",
            "nordic-curl": "Nordic Curl",
            "glute-ham-raise": "Glute Ham Raise",
            "good-morning": "Good Morning",
            "cable-pull-through": "Cable Pull-Through",
            "standing-calf-raise": "Standing Calf Raise",
            "seated-calf-raise": "Seated Calf Raise",
            "donkey-calf-raise": "Donkey Calf Raise",
            "leg-press-calf-raise": "Leg Press Calf Raise",
            "single-leg-calf-raise": "Single-Leg Calf Raise",
            "plank": "Plank",
            "side-plank": "Side Plank",
            "hollow-hold": "Hollow Hold",
            "dead-hang": "Dead Hang",
            "crunch": "Crunch",
            "bicycle-crunch": "Bicycle Crunch",
            "mountain-climber": "Mountain Climber",
            "bird-dog": "Bird Dog",
            "dead-bug": "Dead Bug",
            "bench-crunch": "Bench Crunch",
            "bench-russian-twist": "Bench Russian Twist",
            "bench-leg-lift": "Bench Leg Lift",
            "plank-row": "Plank Row",
            "hanging-leg-raise": "Hanging Leg Raise",
            "toes-to-bar": "Toes to Bar",
            "russian-twist": "Russian Twist",
            "cable-crunch": "Cable Crunch",
            "ab-wheel-rollout": "Ab Wheel Rollout",
            "v-up": "V-Up",
            "flutter-kick": "Flutter Kick",
            "superman": "Superman",
            "sit-up": "Sit-Up",
            "decline-sit-up": "Decline Sit-Up",
            "weighted-sit-up": "Weighted Sit-Up",
            "pallof-press": "Pallof Press",
            "cable-woodchop": "Cable Woodchop",
            "copenhagen-plank": "Copenhagen Plank",
            "kettlebell-swing": "Kettlebell Swing",
            "kettlebell-clean": "Kettlebell Clean",
            "kettlebell-snatch": "Kettlebell Snatch",
            "clean-and-press": "Clean and Press",
            "power-clean": "Power Clean",
            "thruster": "Thruster",
            "farmer-carry": "Farmer's Carry",
            "suitcase-carry": "Suitcase Carry",
            "overhead-carry": "Overhead Carry",
            "sled-push": "Sled Push",
            "wall-ball": "Wall Ball",
            "battle-ropes": "Battle Ropes",
            "box-jump": "Box Jump",
            "burpee": "Burpee",
            "rower": "Rowing Machine",
    ]

    static func name(for id: String, language: AppLanguage = .english, englishFallback: String) -> String {
        _ = language
        return englishNames[id] ?? englishFallback
    }
}
